apiVersion: v1
kind: Service
metadata:
  name: os-project-service 
  labels:
    tag: os-project
spec:
  type: NodePort
  selector:
    tag: os-project

  ports:
  - port: 4200
    targetPort: 4200
    nodePort: 30003
    protocol: TCP
